-- F1.1 — Identity foundation for SEC-001.
--
-- Adds `provider` (which flow created the account) and `google_sub` (Google's
-- stable subject id), then backfills existing rows.
--
-- ORDERING MATTERS. Everything below runs inside a single migration, so the
-- backfill lands in the same transaction as the column that needs it. There is
-- never a moment where `provider` exists but is wrong for a live bdapps user.
--
-- This migration is safe to apply BEFORE the code that reads `provider` ships:
-- the old code ignores unknown columns entirely. Apply it first, confirm the
-- backfill counts, and only then deploy the scoped lookup. Doing it the other
-- way round locks every bdapps user out during the gap.

-- 1. `provider` defaults to 'local' so any row not matched below stays on the
--    email + password flow, which is the conservative choice: 'local' accounts
--    are NOT reachable by /api/auth/bdapps/login once scoping is in place.
ALTER TABLE "public"."User" ADD COLUMN "provider" TEXT NOT NULL DEFAULT 'local';

-- 2. Nullable: only Google-authenticated users ever have one.
ALTER TABLE "public"."User" ADD COLUMN "google_sub" TEXT;

-- 3. Backfill bdapps accounts.
--
--    `bdapps+<digits>@tenant.local` is a reliable marker: it is generated by
--    syntheticEmailForPhone() in app/api/auth/bdapps/login/route.ts, and users
--    cannot change their email — PATCH /api/v1/users/me accepts only
--    `full_name` and `phone` — so the pattern cannot have drifted since signup.
UPDATE "public"."User"
   SET "provider" = 'bdapps'
 WHERE "email" LIKE 'bdapps+%@tenant.local';

-- 4. One account per Google identity. Postgres permits many NULLs under a
--    UNIQUE index, so non-Google users are unaffected.
CREATE UNIQUE INDEX "User_google_sub_key" ON "public"."User"("google_sub");

-- 5. Supports the scoped lookup `WHERE provider = 'bdapps' AND phone = $1`,
--    which is the hot path on every bdapps login.
CREATE INDEX "User_provider_phone_idx" ON "public"."User"("provider", "phone");
